services:
  nginx:
    image: nginx:1.18-alpine
    container_name: nginx
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    ports:
      - "80:80"
    networks:
      - list

  db:
    image: mysql:8.0
    container_name: databs
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - list

  app1:
    image: laksh
    container_name: app1
    env_file: l4ksh1928/listmaker:latest
      - .env
    depends_on:
      - db
    networks: 
      - list

  app2:
    image: l4ksh1928/listmaker:latest
    container_name: app2
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - list


networks:
  list:
    driver: bridge

volumes:
  db_data:
